#!/usr/bin/env ansible-playbook
---

- name: create management groups
  group:
    name: "{{ item.group | default(item.name) | mandatory }}"
    system: true
  loop_control:
    label: "{{ item.group | default(item.name) | mandatory }}"
  with_items: "{{ ansible_usermanagement_users }}"

- name: create management users
  user:
    name: "{{ item.name | mandatory }}"
    group: "{{ item.group | default(item.name) }}"
    comment: "{{ item.comment | default('Managed by Ansible') }}"
  loop_control:
    label: "{{ item.name | mandatory }}"
  with_items: "{{ ansible_usermanagement_users }}"

- name: add authorized keys per user
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ lookup('file', item.1) | mandatory }}"
  loop_control:
    label:
      user: "{{ item.0.name }}"
      key: "{{ item.1 | mandatory }}"
  with_subelements:
    - "{{ ansible_usermanagement_users }}"
    - keys

- name: ensure sudo is installed
  package:
    name: sudo
    state: present

- name: TRANSITION / ensure clean sudoers file
  file:
    path: /etc/sudoers.d/ansible-managed
    state: absent
  when: ansible_usermanagement_transition | default(true)

- name: allow passwordless sudo for users
  lineinfile:
    dest: /etc/sudoers.d/ansible-managed
    create: true
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  loop_control:
    label: "{{ item.group | default(item.name) }}"
  with_items: "{{ ansible_usermanagement_users }}"
